# Use GitHub as the backend for authentication
backend:
  name: github
  repo: B-Munkh/Little-Corner
  branch: main

# Media and Collections sections remain the same
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "timeline"
    label: "Timeline"
    folder: "_timeline"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Event Date", name: "date", widget: "datetime", optional: true, time_format: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Memory Text", name: "body", widget: "markdown" }
      - { label: "Photo", name: "image", widget: "image", required: false }